### obtener todas las reviews
GET http://localhost:3000/api/reviews




### obtener una review
GET http://localhost:3000/api/reviews/1

### crear una review
POST http://localhost:3000/api/reviews/getreviews/user
Content-Type: application/json

{
    "rating": 100,
    "body": "Juegardo",
    "spoiler_check": true,
    "private": false,
    "id": "1",
    "gameId":"652a876a9b4b484ccfd0349d",
    "userId":"65446d97f18a313ca0afc897"
}

### modificar una review
PUT http://localhost:3000/api/reviews/1
Content-Type: application/json

{
      "rating": "73",
      "body": "No tan Juegardo",
      "spoiler_check": false,
      "private": false,
      "id": "1"
}

### borrar una review
DELETE http://localhost:3000/api/reviews/653ea661a8ae5350f44c740f