### obtener todos los juegos
GET http://localhost:3000/api/games

### obtener un juego
GET http://localhost:3000/api/games/3


### obtener un juego por fecha
GET http://localhost:3000/api/games/date/3


### crear un juego
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "The Legend Of Zelda: Tears of the Kingdom",
    "description": "Tras los acontecimientos de The Legend of Zelda: Breath of the Wild, la princesa Zelda junto a Link exploran los cimientos del castillo de Hyrule, en el que encuentran una sala donde reposa un cadáver momificado. Después de que el cadáver tome vida y se levante, ataca a Zelda y Link, dejando a este último malherido y rompiendo el filo de su Espada Maestra. Tras ello desata su poder rompiendo el sello que lo mantenía retenido y se eleva el castillo de Hyrule. Zelda sufre una caída mientras el sitio se derrumba y desaparece mágicamente. Link deberá encontrar a la princesa Zelda por cielo, tierra y subsuelo y así salvar al reino de Hyrule del resurgido Ganondorf, el rey demonio.",
    "cover": "https://i.imgur.com/zJkKrJ3.jpg",
    "banner":"https://i.imgur.com/XsaSiXR.jpg",
    "release_date": "2023-05-12T03:00:00.000Z",
    "website": "",
    "socials": [],
    "rating": 0
}


### crear un juego
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Lies Of P",
    "description": "Lies of P es un soulslike en tercera persona donde el jugador controla al humanoide Pinocho y recorre a pie la ciudad de Krat, explorando el entorno y luchando contra varios enemigos biomecánicos. El jugador usa un arsenal de armas como una espada y un hacha y puede esquivar y bloquear golpes de sus enemigos. Pinocho tiene un brazo mecánico que puede equiparse con dispositivos como un gancho de agarre para atraer a los enemigos o un lanzallamas. El sistema de armas y elaboración ofrece 30 tipos de armas diferentes con 100 combinaciones. El videojuego presenta un Sistema de mentiras donde las decisiones que toma el jugador durante ciertos pasajes afectan el curso de los eventos, lo que lleva a tres finales diferentes. La jugabilidad de Lies of P ha sido llamada soulslike y es comparada con la de Dark Souls y Bloodborne.",
    "cover": "https://i.imgur.com/Cw6PcBO.png",
    "banner": "https://i.imgur.com/xgmwYfz.jpg",
    "release_date": "2023-09-18",
    "website": "",
    "socials": [],
    "rating": 0
}

### crear un juego
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Resident Evil 4 Remake",
    "description": "Resident Evil 4, el legendario survival horror de 2005, se renueva completamente en este remake. Seis años después de los eventos de Resident Evil 2, el sobreviviente de Raccoon City, Leon Kennedy, se encuentra apostado en un recóndito pueblo de Europa para investigar la desaparición de la hija del presidente de los Estados Unidos. Lo que descubre allí no se parece a nada que haya enfrentado antes. Todos los aspectos del juego clásico se han actualizado para la generación actual, desde gráficos y controles modernizados, hasta una historia reinventada que puede sorprender incluso a los fanáticos del juego original.",
    "cover": "https://i.imgur.com/gaKXD7N.jpg",
    "banner": "https://i.imgur.com/2inLywd.jpg",
    "release_date": "2023-03-23",
    "website": "",
    "socials": [],
    "rating": 0
}
### crear un juego
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Baldur's Gate III",
    "description": "Baldur's Gate III es un videojuego de rol que incorpora elementos de juego en solitario y multijugador cooperativo. Los jugadores tienen la posibilidad de crear uno o más personajes y formar un grupo con otros personajes generados por el sistema para avanzar en la trama. De manera alternativa, los jugadores pueden seleccionar uno de sus personajes y unirse en línea con otros jugadores para formar un equipo. A diferencia de las entregas anteriores de la serie Baldur's Gate, Baldur's Gate III presenta un sistema de combate por turnos, similar al de los juegos previos de Larian como Divinity: Original Sin y Divinity: Original Sin II, aunque en esta ocasión, se basa en las reglas de la 5ª edición de D&D.",
    "cover": "https://i.imgur.com/Wz0Jv8e.jpg",
    "banner": "https://i.imgur.com/ywk0zYK.jpg",
    "release_date": "2023-08-03",
    "website": "",
    "socials": [],
    "rating": 0
}
### crear un juego
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Alan Wake II",
    "description": "Saga Anderson es una hábil agente del FBI a la que han llamado para investigar una serie de asesinatos rituales en el pequeño pueblo de Bright Falls del Noroeste del Pacífico. Alan Wake es un escritor que ha pasado años atrapado en el lugar oscuro, una tenebrosa realidad alternativa que puede cambiar de forma con sus palabras. Aunque nunca se hayan visto, los dos están conectados a través de las distintas realidades, y sus acciones pueden alterar sus mundos. Cuando los eventos retratados en una historia de terror envuelven Bright Falls en una oscuridad corruptora y sobrenatural, tanto Anderson como Wake deben usar el poder de la luz para sobrevivir y proteger a sus seres queridos. En un mundo de víctimas y monstruos en el que la realidad puede alterarse, ¿podrán convertirse en los héroes de esta historia?",
    "cover": "https://i.imgur.com/slggzQv.jpg",
    "banner": "https://i.imgur.com/lrw5Q96.jpg",
    "release_date": "2023-10-27",
    "website": "",
    "socials": [],
    "rating": 0
}

### modificar un juego
PUT http://localhost:3000/api/games/2
Content-Type: application/json

{
    "name": "Undertale",
    "description": "sans",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/391540/capsule_616x353.jpg?t=1579096091",
    "release_date": "2015-09-15T03:00:00.000Z",
    "website": "https://undertale.com/",
    "socials": [
      "https://twitter.com/Undertale"
    ],
    "rating": 92
  }

### borrar un juego
DELETE http://localhost:3000/api/games/3