### obtener todas las reviews
GET http://localhost:3000/api/games


### obtener una review
GET http://localhost:3000/api/games/3

### crear una review
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "id": "1",
    "name": "Undertale",
    "description": "sus",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/391540/capsule_616x353.jpg?t=1579096091",
    "release_date": "2015-09-15T03:00:00.000Z",
    "website": "https://undertale.com/",
    "socials": [
      "https://twitter.com/Undertale"
    ],
    "rating": 100
}

### crear una review
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "id": "3",
    "name": "The Legend Of Zelda: Tears of the Kingdom",
    "description": "The Legend of Zelda: Tears of the Kingdom es un videojuego de acción-aventura de 2023 de la serie The Legend of Zelda, desarrollado por la filial Nintendo EPD en colaboración con Monolith Soft y publicado por Nintendo para la consola Nintendo Switch.",
    "cover": "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/2x1_NSwitch_TloZTearsOfTheKingdom_Gamepage.jpg",
    "release_date": "2023-05-12T03:00:00.000Z",
    "website": "",
    "socials": [],
    "rating": 0
}


### modificar una review
PUT http://localhost:3000/api/games/2
Content-Type: application/json

{
    "id": "2",
    "name": "Undertale",
    "description": "sans",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/391540/capsule_616x353.jpg?t=1579096091",
    "release_date": "2015-09-15T03:00:00.000Z",
    "website": "https://undertale.com/",
    "socials": [
      "https://twitter.com/Undertale"
    ],
    "rating": 98
  }

### borrar una review
DELETE http://localhost:3000/api/games/2