### obtener todos los usuarios
GET http://localhost:3000/api/user/


### obtener un usuario
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email":"level@gmail.com",
    "password":"password"
}

### obtener datos del usuario
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE3MWM1MjU5NzM2MDRlNzJkNjA5ZGUiLCJpYXQiOjE2OTYwMTQzMDh9.6Pm5yenS7p8KCiLtfgcwQexe2hwKeXdcf0Qcl3WmpaI

### crear un usuario 1
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "username":"level",
    "email":"level@gmail.com",
    "password":"password"
}

### crear un usuario 2
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "username":"example",
    "email":"example@gmail.com",
    "password":"password"
}

### agregar una review a un usuario
PUT http://localhost:3000/api/user/update
Content-Type: application/json

{
    "_id": ("653ea72c2ee55c002e44093e"),
    "username": "UpdatedUser"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/user/66170532480105b57e347212
